//! Command identifier for low-alloc dispatch (Batch GD).
//!
//! Parse raw command bytes (case-insensitive) into a [`CommandId`] once,
//! then match on the enum instead of re-comparing uppercase strings.

use bytes::Bytes;

/// Known Redis/Kore command. `Unknown` keeps the uppercase name for errors.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum CommandId {
    Acl,
    Append,
    Asking,
    Auth,
    Bgrewriteaof,
    Bgsave,
    Bitcount,
    Bitfield,
    BitfieldRo,
    Bitop,
    Bitpos,
    Blmove,
    Blmpop,
    Blpop,
    Brpop,
    Brpoplpush,
    Bzmpop,
    Bzpopmax,
    Bzpopmin,
    Client,
    Cluster,
    Command,
    Config,
    CopyCmd,
    Dbsize,
    Debug,
    Decr,
    Decrby,
    Del,
    Discard,
    Dump,
    Echo,
    Eval,
    Evalsha,
    EvalshaRo,
    EvalRo,
    Exec,
    Exists,
    Expire,
    Expireat,
    Expiretime,
    Failover,
    Fcall,
    FcallRo,
    Flushall,
    Flushdb,
    FtAliasadd,
    FtAliasdel,
    FtAliasupdate,
    FtCreate,
    FtDropindex,
    FtInfo,
    FtSearch,
    FtTagvals,
    FtList,
    Function,
    Geoadd,
    Geodist,
    Geohash,
    Geopos,
    Georadius,
    Georadiusbymember,
    GeoradiusbymemberRo,
    GeoradiusRo,
    Geosearch,
    Geosearchstore,
    Get,
    Getbit,
    Getdel,
    Getex,
    Getrange,
    Getset,
    Hdel,
    Health,
    Hello,
    Hexists,
    Hget,
    Hgetall,
    Hgetdel,
    Hincrby,
    Hincrbyfloat,
    Hkeys,
    Hlen,
    Hmget,
    Hmset,
    Hrandfield,
    Hscan,
    Hset,
    Hsetnx,
    Hstrlen,
    Hvals,
    Incr,
    Incrby,
    Incrbyfloat,
    Info,
    Keys,
    Lastsave,
    Latency,
    Lcs,
    Lindex,
    Linsert,
    Llen,
    Lmove,
    Lmpop,
    Lolwut,
    Lpop,
    Lpos,
    Lpush,
    Lpushx,
    Lrange,
    Lrem,
    Lset,
    Ltrim,
    Memory,
    Mget,
    Migrate,
    ModuleCmd,
    MoveCmd,
    Mset,
    Msetnx,
    Multi,
    Object,
    Persist,
    Pexpire,
    Pexpireat,
    Pexpiretime,
    Pfadd,
    Pfcount,
    Pfmerge,
    Ping,
    Psetex,
    Psubscribe,
    Psync,
    Pttl,
    Publish,
    Pubsub,
    Punsubscribe,
    Quit,
    Randomkey,
    Readonly,
    Readwrite,
    Rename,
    Renamenx,
    Replconf,
    Replicaof,
    Reset,
    Restore,
    RoleCmd,
    Rpop,
    Rpoplpush,
    Rpush,
    Rpushx,
    Sadd,
    Save,
    Scan,
    Scard,
    Script,
    Sdiff,
    Sdiffstore,
    SelectCmd,
    Sentinel,
    Set,
    Setbit,
    Setex,
    Setnx,
    Setrange,
    Shutdown,
    Sinter,
    Sintercard,
    Sinterstore,
    Sismember,
    Slaveof,
    Slowlog,
    Smembers,
    Smismember,
    Smove,
    Sort,
    Spop,
    Spublish,
    Srandmember,
    Srem,
    Sscan,
    Ssubscribe,
    Strlen,
    Subscribe,
    Substr,
    Sunion,
    Sunionstore,
    Sunsubscribe,
    Swapdb,
    Sweep,
    Sync,
    TimeCmd,
    Touch,
    Ttl,
    TypeCmd,
    Unlink,
    Unsubscribe,
    Unwatch,
    WaitCmd,
    Watch,
    Xack,
    Xadd,
    Xautoclaim,
    Xclaim,
    Xdel,
    Xgroup,
    Xinfo,
    Xlen,
    Xpending,
    Xrange,
    Xread,
    Xreadgroup,
    Xrevrange,
    Xsetid,
    Xtrim,
    Zadd,
    Zcard,
    Zcount,
    Zdiff,
    Zdiffstore,
    Zincrby,
    Zinter,
    Zintercard,
    Zinterstore,
    Zlexcount,
    Zmpop,
    Zmscore,
    Zpopmax,
    Zpopmin,
    Zrandmember,
    Zrange,
    Zrangebylex,
    Zrangebyscore,
    Zrangestore,
    Zrank,
    Zrem,
    Zremrangebylex,
    Zremrangebyrank,
    Zremrangebyscore,
    Zrevrange,
    Zrevrangebylex,
    Zrevrangebyscore,
    Zrevrank,
    Zscan,
    Zscore,
    Zunion,
    Zunionstore,
    Unknown,
}

impl CommandId {
    /// Identify from **already uppercased** ASCII command name bytes.
    #[inline]
    pub fn from_upper(name: &[u8]) -> Self {
        // Length-first branches keep the SET/GET/PING path tiny.
        match name.len() {
            3 => match name {
                b"ACL" => CommandId::Acl,
                b"DEL" => CommandId::Del,
                b"GET" => CommandId::Get,
                b"LCS" => CommandId::Lcs,
                b"SET" => CommandId::Set,
                b"TTL" => CommandId::Ttl,
                _ => CommandId::Unknown,
            },
            4 => match name {
                b"AUTH" => CommandId::Auth,
                b"COPY" => CommandId::CopyCmd,
                b"DECR" => CommandId::Decr,
                b"DUMP" => CommandId::Dump,
                b"ECHO" => CommandId::Echo,
                b"EVAL" => CommandId::Eval,
                b"EXEC" => CommandId::Exec,
                b"HDEL" => CommandId::Hdel,
                b"HGET" => CommandId::Hget,
                b"HLEN" => CommandId::Hlen,
                b"HSET" => CommandId::Hset,
                b"INCR" => CommandId::Incr,
                b"INFO" => CommandId::Info,
                b"KEYS" => CommandId::Keys,
                b"LLEN" => CommandId::Llen,
                b"LPOP" => CommandId::Lpop,
                b"LPOS" => CommandId::Lpos,
                b"LREM" => CommandId::Lrem,
                b"LSET" => CommandId::Lset,
                b"MGET" => CommandId::Mget,
                b"MOVE" => CommandId::MoveCmd,
                b"MSET" => CommandId::Mset,
                b"PING" => CommandId::Ping,
                b"PTTL" => CommandId::Pttl,
                b"QUIT" => CommandId::Quit,
                b"ROLE" => CommandId::RoleCmd,
                b"RPOP" => CommandId::Rpop,
                b"SADD" => CommandId::Sadd,
                b"SAVE" => CommandId::Save,
                b"SCAN" => CommandId::Scan,
                b"SORT" => CommandId::Sort,
                b"SPOP" => CommandId::Spop,
                b"SREM" => CommandId::Srem,
                b"SYNC" => CommandId::Sync,
                b"TIME" => CommandId::TimeCmd,
                b"TYPE" => CommandId::TypeCmd,
                b"WAIT" => CommandId::WaitCmd,
                b"XACK" => CommandId::Xack,
                b"XADD" => CommandId::Xadd,
                b"XDEL" => CommandId::Xdel,
                b"XLEN" => CommandId::Xlen,
                b"ZADD" => CommandId::Zadd,
                b"ZREM" => CommandId::Zrem,
                _ => CommandId::Unknown,
            },
            5 => match name {
                b"BITOP" => CommandId::Bitop,
                b"BLPOP" => CommandId::Blpop,
                b"BRPOP" => CommandId::Brpop,
                b"DEBUG" => CommandId::Debug,
                b"FCALL" => CommandId::Fcall,
                b"GETEX" => CommandId::Getex,
                b"HELLO" => CommandId::Hello,
                b"HKEYS" => CommandId::Hkeys,
                b"HMGET" => CommandId::Hmget,
                b"HMSET" => CommandId::Hmset,
                b"HSCAN" => CommandId::Hscan,
                b"HVALS" => CommandId::Hvals,
                b"LMOVE" => CommandId::Lmove,
                b"LMPOP" => CommandId::Lmpop,
                b"LPUSH" => CommandId::Lpush,
                b"LTRIM" => CommandId::Ltrim,
                b"MULTI" => CommandId::Multi,
                b"PFADD" => CommandId::Pfadd,
                b"PSYNC" => CommandId::Psync,
                b"RESET" => CommandId::Reset,
                b"RPUSH" => CommandId::Rpush,
                b"SCARD" => CommandId::Scard,
                b"SDIFF" => CommandId::Sdiff,
                b"SETEX" => CommandId::Setex,
                b"SETNX" => CommandId::Setnx,
                b"SMOVE" => CommandId::Smove,
                b"SSCAN" => CommandId::Sscan,
                b"SWEEP" => CommandId::Sweep,
                b"TOUCH" => CommandId::Touch,
                b"WATCH" => CommandId::Watch,
                b"XINFO" => CommandId::Xinfo,
                b"XREAD" => CommandId::Xread,
                b"XTRIM" => CommandId::Xtrim,
                b"ZCARD" => CommandId::Zcard,
                b"ZDIFF" => CommandId::Zdiff,
                b"ZMPOP" => CommandId::Zmpop,
                b"ZRANK" => CommandId::Zrank,
                b"ZSCAN" => CommandId::Zscan,
                _ => CommandId::Unknown,
            },
            6 => match name {
                b"APPEND" => CommandId::Append,
                b"ASKING" => CommandId::Asking,
                b"BGSAVE" => CommandId::Bgsave,
                b"BITPOS" => CommandId::Bitpos,
                b"BLMOVE" => CommandId::Blmove,
                b"BLMPOP" => CommandId::Blmpop,
                b"BZMPOP" => CommandId::Bzmpop,
                b"CLIENT" => CommandId::Client,
                b"CONFIG" => CommandId::Config,
                b"DBSIZE" => CommandId::Dbsize,
                b"DECRBY" => CommandId::Decrby,
                b"EXISTS" => CommandId::Exists,
                b"EXPIRE" => CommandId::Expire,
                b"GEOADD" => CommandId::Geoadd,
                b"GEOPOS" => CommandId::Geopos,
                b"GETBIT" => CommandId::Getbit,
                b"GETDEL" => CommandId::Getdel,
                b"GETSET" => CommandId::Getset,
                b"HEALTH" => CommandId::Health,
                b"HSETNX" => CommandId::Hsetnx,
                b"INCRBY" => CommandId::Incrby,
                b"LINDEX" => CommandId::Lindex,
                b"LOLWUT" => CommandId::Lolwut,
                b"LPUSHX" => CommandId::Lpushx,
                b"LRANGE" => CommandId::Lrange,
                b"MEMORY" => CommandId::Memory,
                b"MODULE" => CommandId::ModuleCmd,
                b"MSETNX" => CommandId::Msetnx,
                b"OBJECT" => CommandId::Object,
                b"PSETEX" => CommandId::Psetex,
                b"PUBSUB" => CommandId::Pubsub,
                b"RENAME" => CommandId::Rename,
                b"RPUSHX" => CommandId::Rpushx,
                b"SCRIPT" => CommandId::Script,
                b"SELECT" => CommandId::SelectCmd,
                b"SETBIT" => CommandId::Setbit,
                b"SINTER" => CommandId::Sinter,
                b"STRLEN" => CommandId::Strlen,
                b"SUBSTR" => CommandId::Substr,
                b"SUNION" => CommandId::Sunion,
                b"SWAPDB" => CommandId::Swapdb,
                b"UNLINK" => CommandId::Unlink,
                b"XCLAIM" => CommandId::Xclaim,
                b"XGROUP" => CommandId::Xgroup,
                b"XRANGE" => CommandId::Xrange,
                b"XSETID" => CommandId::Xsetid,
                b"ZCOUNT" => CommandId::Zcount,
                b"ZINTER" => CommandId::Zinter,
                b"ZRANGE" => CommandId::Zrange,
                b"ZSCORE" => CommandId::Zscore,
                b"ZUNION" => CommandId::Zunion,
                _ => CommandId::Unknown,
            },
            7 => match name {
                b"CLUSTER" => CommandId::Cluster,
                b"COMMAND" => CommandId::Command,
                b"DISCARD" => CommandId::Discard,
                b"EVALSHA" => CommandId::Evalsha,
                b"EVAL_RO" => CommandId::EvalRo,
                b"FLUSHDB" => CommandId::Flushdb,
                b"FT.INFO" => CommandId::FtInfo,
                b"GEODIST" => CommandId::Geodist,
                b"GEOHASH" => CommandId::Geohash,
                b"HEXISTS" => CommandId::Hexists,
                b"HGETALL" => CommandId::Hgetall,
                b"HGETDEL" => CommandId::Hgetdel,
                b"HINCRBY" => CommandId::Hincrby,
                b"HSTRLEN" => CommandId::Hstrlen,
                b"LATENCY" => CommandId::Latency,
                b"LINSERT" => CommandId::Linsert,
                b"MIGRATE" => CommandId::Migrate,
                b"PERSIST" => CommandId::Persist,
                b"PEXPIRE" => CommandId::Pexpire,
                b"PFCOUNT" => CommandId::Pfcount,
                b"PFMERGE" => CommandId::Pfmerge,
                b"PUBLISH" => CommandId::Publish,
                b"RESTORE" => CommandId::Restore,
                b"SLAVEOF" => CommandId::Slaveof,
                b"SLOWLOG" => CommandId::Slowlog,
                b"UNWATCH" => CommandId::Unwatch,
                b"ZINCRBY" => CommandId::Zincrby,
                b"ZMSCORE" => CommandId::Zmscore,
                b"ZPOPMAX" => CommandId::Zpopmax,
                b"ZPOPMIN" => CommandId::Zpopmin,
                _ => CommandId::Unknown,
            },
            8 => match name {
                b"BITCOUNT" => CommandId::Bitcount,
                b"BITFIELD" => CommandId::Bitfield,
                b"BZPOPMAX" => CommandId::Bzpopmax,
                b"BZPOPMIN" => CommandId::Bzpopmin,
                b"EXPIREAT" => CommandId::Expireat,
                b"FAILOVER" => CommandId::Failover,
                b"FCALL_RO" => CommandId::FcallRo,
                b"FLUSHALL" => CommandId::Flushall,
                b"FT._LIST" => CommandId::FtList,
                b"FUNCTION" => CommandId::Function,
                b"GETRANGE" => CommandId::Getrange,
                b"LASTSAVE" => CommandId::Lastsave,
                b"READONLY" => CommandId::Readonly,
                b"RENAMENX" => CommandId::Renamenx,
                b"REPLCONF" => CommandId::Replconf,
                b"SENTINEL" => CommandId::Sentinel,
                b"SETRANGE" => CommandId::Setrange,
                b"SHUTDOWN" => CommandId::Shutdown,
                b"SMEMBERS" => CommandId::Smembers,
                b"SPUBLISH" => CommandId::Spublish,
                b"XPENDING" => CommandId::Xpending,
                b"ZREVRANK" => CommandId::Zrevrank,
                _ => CommandId::Unknown,
            },
            9 => match name {
                b"FT.CREATE" => CommandId::FtCreate,
                b"FT.SEARCH" => CommandId::FtSearch,
                b"GEORADIUS" => CommandId::Georadius,
                b"GEOSEARCH" => CommandId::Geosearch,
                b"PEXPIREAT" => CommandId::Pexpireat,
                b"RANDOMKEY" => CommandId::Randomkey,
                b"READWRITE" => CommandId::Readwrite,
                b"REPLICAOF" => CommandId::Replicaof,
                b"RPOPLPUSH" => CommandId::Rpoplpush,
                b"SISMEMBER" => CommandId::Sismember,
                b"SUBSCRIBE" => CommandId::Subscribe,
                b"XREVRANGE" => CommandId::Xrevrange,
                b"ZLEXCOUNT" => CommandId::Zlexcount,
                b"ZREVRANGE" => CommandId::Zrevrange,
                _ => CommandId::Unknown,
            },
            10 => match name {
                b"BRPOPLPUSH" => CommandId::Brpoplpush,
                b"EVALSHA_RO" => CommandId::EvalshaRo,
                b"EXPIRETIME" => CommandId::Expiretime,
                b"FT.TAGVALS" => CommandId::FtTagvals,
                b"HRANDFIELD" => CommandId::Hrandfield,
                b"PSUBSCRIBE" => CommandId::Psubscribe,
                b"SDIFFSTORE" => CommandId::Sdiffstore,
                b"SINTERCARD" => CommandId::Sintercard,
                b"SMISMEMBER" => CommandId::Smismember,
                b"SSUBSCRIBE" => CommandId::Ssubscribe,
                b"XAUTOCLAIM" => CommandId::Xautoclaim,
                b"XREADGROUP" => CommandId::Xreadgroup,
                b"ZDIFFSTORE" => CommandId::Zdiffstore,
                b"ZINTERCARD" => CommandId::Zintercard,
                _ => CommandId::Unknown,
            },
            11 => match name {
                b"BITFIELD_RO" => CommandId::BitfieldRo,
                b"FT.ALIASADD" => CommandId::FtAliasadd,
                b"FT.ALIASDEL" => CommandId::FtAliasdel,
                b"INCRBYFLOAT" => CommandId::Incrbyfloat,
                b"PEXPIRETIME" => CommandId::Pexpiretime,
                b"SINTERSTORE" => CommandId::Sinterstore,
                b"SRANDMEMBER" => CommandId::Srandmember,
                b"SUNIONSTORE" => CommandId::Sunionstore,
                b"UNSUBSCRIBE" => CommandId::Unsubscribe,
                b"ZINTERSTORE" => CommandId::Zinterstore,
                b"ZRANDMEMBER" => CommandId::Zrandmember,
                b"ZRANGEBYLEX" => CommandId::Zrangebylex,
                b"ZRANGESTORE" => CommandId::Zrangestore,
                b"ZUNIONSTORE" => CommandId::Zunionstore,
                _ => CommandId::Unknown,
            },
            12 => match name {
                b"BGREWRITEAOF" => CommandId::Bgrewriteaof,
                b"FT.DROPINDEX" => CommandId::FtDropindex,
                b"GEORADIUS_RO" => CommandId::GeoradiusRo,
                b"HINCRBYFLOAT" => CommandId::Hincrbyfloat,
                b"PUNSUBSCRIBE" => CommandId::Punsubscribe,
                b"SUNSUBSCRIBE" => CommandId::Sunsubscribe,
                _ => CommandId::Unknown,
            },
            13 => match name {
                b"ZRANGEBYSCORE" => CommandId::Zrangebyscore,
                _ => CommandId::Unknown,
            },
            14 => match name {
                b"FT.ALIASUPDATE" => CommandId::FtAliasupdate,
                b"GEOSEARCHSTORE" => CommandId::Geosearchstore,
                b"ZREMRANGEBYLEX" => CommandId::Zremrangebylex,
                b"ZREVRANGEBYLEX" => CommandId::Zrevrangebylex,
                _ => CommandId::Unknown,
            },
            15 => match name {
                b"ZREMRANGEBYRANK" => CommandId::Zremrangebyrank,
                _ => CommandId::Unknown,
            },
            16 => match name {
                b"ZREMRANGEBYSCORE" => CommandId::Zremrangebyscore,
                b"ZREVRANGEBYSCORE" => CommandId::Zrevrangebyscore,
                _ => CommandId::Unknown,
            },
            17 => match name {
                b"GEORADIUSBYMEMBER" => CommandId::Georadiusbymember,
                _ => CommandId::Unknown,
            },
            20 => match name {
                b"GEORADIUSBYMEMBER_RO" => CommandId::GeoradiusbymemberRo,
                _ => CommandId::Unknown,
            },
            _ => CommandId::Unknown,
        }
    }

    /// Static RESP bulk name for AOF/repl argv (hot writes).
    #[inline]
    pub fn static_name(self) -> Option<Bytes> {
        Some(match self {
            CommandId::Append => Bytes::from_static(b"APPEND"),
            CommandId::Decr => Bytes::from_static(b"DECR"),
            CommandId::Decrby => Bytes::from_static(b"DECRBY"),
            CommandId::Del => Bytes::from_static(b"DEL"),
            CommandId::Exists => Bytes::from_static(b"EXISTS"),
            CommandId::Expire => Bytes::from_static(b"EXPIRE"),
            CommandId::Flushall => Bytes::from_static(b"FLUSHALL"),
            CommandId::Flushdb => Bytes::from_static(b"FLUSHDB"),
            CommandId::Get => Bytes::from_static(b"GET"),
            CommandId::Getdel => Bytes::from_static(b"GETDEL"),
            CommandId::Hdel => Bytes::from_static(b"HDEL"),
            CommandId::Hset => Bytes::from_static(b"HSET"),
            CommandId::Incr => Bytes::from_static(b"INCR"),
            CommandId::Incrby => Bytes::from_static(b"INCRBY"),
            CommandId::Lpop => Bytes::from_static(b"LPOP"),
            CommandId::Lpush => Bytes::from_static(b"LPUSH"),
            CommandId::Mget => Bytes::from_static(b"MGET"),
            CommandId::Mset => Bytes::from_static(b"MSET"),
            CommandId::Pexpire => Bytes::from_static(b"PEXPIRE"),
            CommandId::Ping => Bytes::from_static(b"PING"),
            CommandId::Pttl => Bytes::from_static(b"PTTL"),
            CommandId::Rpop => Bytes::from_static(b"RPOP"),
            CommandId::Rpush => Bytes::from_static(b"RPUSH"),
            CommandId::Sadd => Bytes::from_static(b"SADD"),
            CommandId::Set => Bytes::from_static(b"SET"),
            CommandId::Setnx => Bytes::from_static(b"SETNX"),
            CommandId::Srem => Bytes::from_static(b"SREM"),
            CommandId::Ttl => Bytes::from_static(b"TTL"),
            CommandId::Unlink => Bytes::from_static(b"UNLINK"),
            CommandId::Xadd => Bytes::from_static(b"XADD"),
            CommandId::Zadd => Bytes::from_static(b"ZADD"),
            CommandId::Zrem => Bytes::from_static(b"ZREM"),
            _ => return None,
        })
    }

    /// Whether this command mutates keyspace / server state.
    #[inline]
    pub fn is_write(self) -> bool {
        matches!(self,
            CommandId::Append | CommandId::Bitfield | CommandId::Bitop | CommandId::Blmove
            |
            CommandId::Blmpop | CommandId::Blpop | CommandId::Brpop | CommandId::Brpoplpush
            |
            CommandId::Bzmpop | CommandId::Bzpopmax | CommandId::Bzpopmin | CommandId::CopyCmd
            |
            CommandId::Decr | CommandId::Decrby | CommandId::Del | CommandId::Eval
            |
            CommandId::Evalsha | CommandId::Expire | CommandId::Expireat | CommandId::Fcall
            |
            CommandId::Flushall | CommandId::Flushdb | CommandId::FtAliasadd | CommandId::FtAliasdel
            |
            CommandId::FtAliasupdate | CommandId::FtCreate | CommandId::FtDropindex | CommandId::Function
            |
            CommandId::Geoadd | CommandId::Georadius | CommandId::Georadiusbymember | CommandId::Geosearchstore
            |
            CommandId::Getdel | CommandId::Getex | CommandId::Getset | CommandId::Hdel
            |
            CommandId::Hgetdel | CommandId::Hincrby | CommandId::Hincrbyfloat | CommandId::Hmset
            |
            CommandId::Hset | CommandId::Hsetnx | CommandId::Incr | CommandId::Incrby
            |
            CommandId::Incrbyfloat | CommandId::Linsert | CommandId::Lmove | CommandId::Lmpop
            |
            CommandId::Lpop | CommandId::Lpush | CommandId::Lpushx | CommandId::Lrem
            |
            CommandId::Lset | CommandId::Ltrim | CommandId::Migrate | CommandId::MoveCmd
            |
            CommandId::Mset | CommandId::Msetnx | CommandId::Persist | CommandId::Pexpire
            |
            CommandId::Pexpireat | CommandId::Pfadd | CommandId::Pfmerge | CommandId::Psetex
            |
            CommandId::Rename | CommandId::Renamenx | CommandId::Restore | CommandId::Rpop
            |
            CommandId::Rpoplpush | CommandId::Rpush | CommandId::Rpushx | CommandId::Sadd
            |
            CommandId::Sdiffstore | CommandId::Set | CommandId::Setbit | CommandId::Setex
            |
            CommandId::Setnx | CommandId::Setrange | CommandId::Sinterstore | CommandId::Smove
            |
            CommandId::Spop | CommandId::Srem | CommandId::Sunionstore | CommandId::Swapdb
            |
            CommandId::Touch | CommandId::Unlink | CommandId::Xack | CommandId::Xadd
            |
            CommandId::Xautoclaim | CommandId::Xclaim | CommandId::Xdel | CommandId::Xgroup
            |
            CommandId::Xreadgroup | CommandId::Xsetid | CommandId::Xtrim | CommandId::Zadd
            |
            CommandId::Zdiffstore | CommandId::Zincrby | CommandId::Zinterstore | CommandId::Zmpop
            |
            CommandId::Zpopmax | CommandId::Zpopmin | CommandId::Zrangestore | CommandId::Zrem
            |
            CommandId::Zremrangebylex | CommandId::Zremrangebyrank | CommandId::Zremrangebyscore | CommandId::Zunionstore
        )
    }

    /// Uppercase name for ACL / errors when known; `None` for Unknown.
    #[inline]
    #[allow(dead_code)] // reserved for catalog / error paths outside hot dispatch
    pub fn name_upper(self) -> Option<&'static str> {
        Some(match self {
            CommandId::Acl => "ACL",
            CommandId::Append => "APPEND",
            CommandId::Asking => "ASKING",
            CommandId::Auth => "AUTH",
            CommandId::Bgrewriteaof => "BGREWRITEAOF",
            CommandId::Bgsave => "BGSAVE",
            CommandId::Bitcount => "BITCOUNT",
            CommandId::Bitfield => "BITFIELD",
            CommandId::BitfieldRo => "BITFIELD_RO",
            CommandId::Bitop => "BITOP",
            CommandId::Bitpos => "BITPOS",
            CommandId::Blmove => "BLMOVE",
            CommandId::Blmpop => "BLMPOP",
            CommandId::Blpop => "BLPOP",
            CommandId::Brpop => "BRPOP",
            CommandId::Brpoplpush => "BRPOPLPUSH",
            CommandId::Bzmpop => "BZMPOP",
            CommandId::Bzpopmax => "BZPOPMAX",
            CommandId::Bzpopmin => "BZPOPMIN",
            CommandId::Client => "CLIENT",
            CommandId::Cluster => "CLUSTER",
            CommandId::Command => "COMMAND",
            CommandId::Config => "CONFIG",
            CommandId::CopyCmd => "COPY",
            CommandId::Dbsize => "DBSIZE",
            CommandId::Debug => "DEBUG",
            CommandId::Decr => "DECR",
            CommandId::Decrby => "DECRBY",
            CommandId::Del => "DEL",
            CommandId::Discard => "DISCARD",
            CommandId::Dump => "DUMP",
            CommandId::Echo => "ECHO",
            CommandId::Eval => "EVAL",
            CommandId::Evalsha => "EVALSHA",
            CommandId::EvalshaRo => "EVALSHA_RO",
            CommandId::EvalRo => "EVAL_RO",
            CommandId::Exec => "EXEC",
            CommandId::Exists => "EXISTS",
            CommandId::Expire => "EXPIRE",
            CommandId::Expireat => "EXPIREAT",
            CommandId::Expiretime => "EXPIRETIME",
            CommandId::Failover => "FAILOVER",
            CommandId::Fcall => "FCALL",
            CommandId::FcallRo => "FCALL_RO",
            CommandId::Flushall => "FLUSHALL",
            CommandId::Flushdb => "FLUSHDB",
            CommandId::FtAliasadd => "FT.ALIASADD",
            CommandId::FtAliasdel => "FT.ALIASDEL",
            CommandId::FtAliasupdate => "FT.ALIASUPDATE",
            CommandId::FtCreate => "FT.CREATE",
            CommandId::FtDropindex => "FT.DROPINDEX",
            CommandId::FtInfo => "FT.INFO",
            CommandId::FtSearch => "FT.SEARCH",
            CommandId::FtTagvals => "FT.TAGVALS",
            CommandId::FtList => "FT._LIST",
            CommandId::Function => "FUNCTION",
            CommandId::Geoadd => "GEOADD",
            CommandId::Geodist => "GEODIST",
            CommandId::Geohash => "GEOHASH",
            CommandId::Geopos => "GEOPOS",
            CommandId::Georadius => "GEORADIUS",
            CommandId::Georadiusbymember => "GEORADIUSBYMEMBER",
            CommandId::GeoradiusbymemberRo => "GEORADIUSBYMEMBER_RO",
            CommandId::GeoradiusRo => "GEORADIUS_RO",
            CommandId::Geosearch => "GEOSEARCH",
            CommandId::Geosearchstore => "GEOSEARCHSTORE",
            CommandId::Get => "GET",
            CommandId::Getbit => "GETBIT",
            CommandId::Getdel => "GETDEL",
            CommandId::Getex => "GETEX",
            CommandId::Getrange => "GETRANGE",
            CommandId::Getset => "GETSET",
            CommandId::Hdel => "HDEL",
            CommandId::Health => "HEALTH",
            CommandId::Hello => "HELLO",
            CommandId::Hexists => "HEXISTS",
            CommandId::Hget => "HGET",
            CommandId::Hgetall => "HGETALL",
            CommandId::Hgetdel => "HGETDEL",
            CommandId::Hincrby => "HINCRBY",
            CommandId::Hincrbyfloat => "HINCRBYFLOAT",
            CommandId::Hkeys => "HKEYS",
            CommandId::Hlen => "HLEN",
            CommandId::Hmget => "HMGET",
            CommandId::Hmset => "HMSET",
            CommandId::Hrandfield => "HRANDFIELD",
            CommandId::Hscan => "HSCAN",
            CommandId::Hset => "HSET",
            CommandId::Hsetnx => "HSETNX",
            CommandId::Hstrlen => "HSTRLEN",
            CommandId::Hvals => "HVALS",
            CommandId::Incr => "INCR",
            CommandId::Incrby => "INCRBY",
            CommandId::Incrbyfloat => "INCRBYFLOAT",
            CommandId::Info => "INFO",
            CommandId::Keys => "KEYS",
            CommandId::Lastsave => "LASTSAVE",
            CommandId::Latency => "LATENCY",
            CommandId::Lcs => "LCS",
            CommandId::Lindex => "LINDEX",
            CommandId::Linsert => "LINSERT",
            CommandId::Llen => "LLEN",
            CommandId::Lmove => "LMOVE",
            CommandId::Lmpop => "LMPOP",
            CommandId::Lolwut => "LOLWUT",
            CommandId::Lpop => "LPOP",
            CommandId::Lpos => "LPOS",
            CommandId::Lpush => "LPUSH",
            CommandId::Lpushx => "LPUSHX",
            CommandId::Lrange => "LRANGE",
            CommandId::Lrem => "LREM",
            CommandId::Lset => "LSET",
            CommandId::Ltrim => "LTRIM",
            CommandId::Memory => "MEMORY",
            CommandId::Mget => "MGET",
            CommandId::Migrate => "MIGRATE",
            CommandId::ModuleCmd => "MODULE",
            CommandId::MoveCmd => "MOVE",
            CommandId::Mset => "MSET",
            CommandId::Msetnx => "MSETNX",
            CommandId::Multi => "MULTI",
            CommandId::Object => "OBJECT",
            CommandId::Persist => "PERSIST",
            CommandId::Pexpire => "PEXPIRE",
            CommandId::Pexpireat => "PEXPIREAT",
            CommandId::Pexpiretime => "PEXPIRETIME",
            CommandId::Pfadd => "PFADD",
            CommandId::Pfcount => "PFCOUNT",
            CommandId::Pfmerge => "PFMERGE",
            CommandId::Ping => "PING",
            CommandId::Psetex => "PSETEX",
            CommandId::Psubscribe => "PSUBSCRIBE",
            CommandId::Psync => "PSYNC",
            CommandId::Pttl => "PTTL",
            CommandId::Publish => "PUBLISH",
            CommandId::Pubsub => "PUBSUB",
            CommandId::Punsubscribe => "PUNSUBSCRIBE",
            CommandId::Quit => "QUIT",
            CommandId::Randomkey => "RANDOMKEY",
            CommandId::Readonly => "READONLY",
            CommandId::Readwrite => "READWRITE",
            CommandId::Rename => "RENAME",
            CommandId::Renamenx => "RENAMENX",
            CommandId::Replconf => "REPLCONF",
            CommandId::Replicaof => "REPLICAOF",
            CommandId::Reset => "RESET",
            CommandId::Restore => "RESTORE",
            CommandId::RoleCmd => "ROLE",
            CommandId::Rpop => "RPOP",
            CommandId::Rpoplpush => "RPOPLPUSH",
            CommandId::Rpush => "RPUSH",
            CommandId::Rpushx => "RPUSHX",
            CommandId::Sadd => "SADD",
            CommandId::Save => "SAVE",
            CommandId::Scan => "SCAN",
            CommandId::Scard => "SCARD",
            CommandId::Script => "SCRIPT",
            CommandId::Sdiff => "SDIFF",
            CommandId::Sdiffstore => "SDIFFSTORE",
            CommandId::SelectCmd => "SELECT",
            CommandId::Sentinel => "SENTINEL",
            CommandId::Set => "SET",
            CommandId::Setbit => "SETBIT",
            CommandId::Setex => "SETEX",
            CommandId::Setnx => "SETNX",
            CommandId::Setrange => "SETRANGE",
            CommandId::Shutdown => "SHUTDOWN",
            CommandId::Sinter => "SINTER",
            CommandId::Sintercard => "SINTERCARD",
            CommandId::Sinterstore => "SINTERSTORE",
            CommandId::Sismember => "SISMEMBER",
            CommandId::Slaveof => "SLAVEOF",
            CommandId::Slowlog => "SLOWLOG",
            CommandId::Smembers => "SMEMBERS",
            CommandId::Smismember => "SMISMEMBER",
            CommandId::Smove => "SMOVE",
            CommandId::Sort => "SORT",
            CommandId::Spop => "SPOP",
            CommandId::Spublish => "SPUBLISH",
            CommandId::Srandmember => "SRANDMEMBER",
            CommandId::Srem => "SREM",
            CommandId::Sscan => "SSCAN",
            CommandId::Ssubscribe => "SSUBSCRIBE",
            CommandId::Strlen => "STRLEN",
            CommandId::Subscribe => "SUBSCRIBE",
            CommandId::Substr => "SUBSTR",
            CommandId::Sunion => "SUNION",
            CommandId::Sunionstore => "SUNIONSTORE",
            CommandId::Sunsubscribe => "SUNSUBSCRIBE",
            CommandId::Swapdb => "SWAPDB",
            CommandId::Sweep => "SWEEP",
            CommandId::Sync => "SYNC",
            CommandId::TimeCmd => "TIME",
            CommandId::Touch => "TOUCH",
            CommandId::Ttl => "TTL",
            CommandId::TypeCmd => "TYPE",
            CommandId::Unlink => "UNLINK",
            CommandId::Unsubscribe => "UNSUBSCRIBE",
            CommandId::Unwatch => "UNWATCH",
            CommandId::WaitCmd => "WAIT",
            CommandId::Watch => "WATCH",
            CommandId::Xack => "XACK",
            CommandId::Xadd => "XADD",
            CommandId::Xautoclaim => "XAUTOCLAIM",
            CommandId::Xclaim => "XCLAIM",
            CommandId::Xdel => "XDEL",
            CommandId::Xgroup => "XGROUP",
            CommandId::Xinfo => "XINFO",
            CommandId::Xlen => "XLEN",
            CommandId::Xpending => "XPENDING",
            CommandId::Xrange => "XRANGE",
            CommandId::Xread => "XREAD",
            CommandId::Xreadgroup => "XREADGROUP",
            CommandId::Xrevrange => "XREVRANGE",
            CommandId::Xsetid => "XSETID",
            CommandId::Xtrim => "XTRIM",
            CommandId::Zadd => "ZADD",
            CommandId::Zcard => "ZCARD",
            CommandId::Zcount => "ZCOUNT",
            CommandId::Zdiff => "ZDIFF",
            CommandId::Zdiffstore => "ZDIFFSTORE",
            CommandId::Zincrby => "ZINCRBY",
            CommandId::Zinter => "ZINTER",
            CommandId::Zintercard => "ZINTERCARD",
            CommandId::Zinterstore => "ZINTERSTORE",
            CommandId::Zlexcount => "ZLEXCOUNT",
            CommandId::Zmpop => "ZMPOP",
            CommandId::Zmscore => "ZMSCORE",
            CommandId::Zpopmax => "ZPOPMAX",
            CommandId::Zpopmin => "ZPOPMIN",
            CommandId::Zrandmember => "ZRANDMEMBER",
            CommandId::Zrange => "ZRANGE",
            CommandId::Zrangebylex => "ZRANGEBYLEX",
            CommandId::Zrangebyscore => "ZRANGEBYSCORE",
            CommandId::Zrangestore => "ZRANGESTORE",
            CommandId::Zrank => "ZRANK",
            CommandId::Zrem => "ZREM",
            CommandId::Zremrangebylex => "ZREMRANGEBYLEX",
            CommandId::Zremrangebyrank => "ZREMRANGEBYRANK",
            CommandId::Zremrangebyscore => "ZREMRANGEBYSCORE",
            CommandId::Zrevrange => "ZREVRANGE",
            CommandId::Zrevrangebylex => "ZREVRANGEBYLEX",
            CommandId::Zrevrangebyscore => "ZREVRANGEBYSCORE",
            CommandId::Zrevrank => "ZREVRANK",
            CommandId::Zscan => "ZSCAN",
            CommandId::Zscore => "ZSCORE",
            CommandId::Zunion => "ZUNION",
            CommandId::Zunionstore => "ZUNIONSTORE",
            CommandId::Unknown => return None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn identifies_hot_path_case_insensitive_via_upper() {
        assert_eq!(CommandId::from_upper(b"SET"), CommandId::Set);
        assert_eq!(CommandId::from_upper(b"GET"), CommandId::Get);
        assert_eq!(CommandId::from_upper(b"PING"), CommandId::Ping);
        assert!(CommandId::Set.is_write());
        assert!(!CommandId::Get.is_write());
        assert_eq!(CommandId::Set.static_name().unwrap().as_ref(), b"SET");
    }
    #[test]
    fn unknown_and_aliases() {
        assert_eq!(CommandId::from_upper(b"NOPE"), CommandId::Unknown);
        assert_eq!(CommandId::from_upper(b"SLAVEOF"), CommandId::Slaveof);
        assert_eq!(CommandId::from_upper(b"REPLICAOF"), CommandId::Replicaof);
    }
}
