pub mod cache;
pub mod entry;
pub mod hashmap;
pub mod network;
pub mod protocol;
pub mod commands;
pub mod stats;
pub mod config;
pub mod error;
pub mod sorted_set;
pub mod geospatial;
pub mod redlock;
pub mod deadlock;
pub mod fair_queue;
pub mod pubsub;
pub mod memory;
pub mod search_index;
pub mod query_engine;
pub mod vector_search;

pub use cache::Cache;
pub use config::Config;
pub use error::{Error, Result};
pub use network::Server;
pub use sorted_set::SortedSet;
pub use geospatial::{GeoSet, GeoPoint, DistanceUnit};
pub use redlock::{Redlock, Lock};
pub use deadlock::{DeadlockDetector, DeadlockStatus, LockInfo};
pub use fair_queue::{FairQueue, QueuedClient, FairQueueStats};
pub use pubsub::{PubSub, ClientId};
pub use memory::{MemoryTracker, MemoryCategory};
pub use search_index::{SearchIndexManager, IndexDefinition, FieldDefinition, FieldType, DocumentField, DistanceMetric, VectorAlgorithm};
pub use query_engine::{Query, QueryFilter, QueryExecutor};
pub use vector_search::{VectorIndex, VectorSearchResult};

